# Introduction to Numpy

**Author:** ChatGPT & Tran Thu Le  
**Date:** 20/02/2023

**Abstract.** NumPy is a Python library that stands for “Numerical Python”. In this tutorial, we will cover the basics of NumPy and show you how to use this library to work with matrices and vectors.

To use NumPy, we need to import it. We can do this using the following code:

In [1]:
import numpy as np

## Creating NumPy Arrays
The primary data structure in NumPy is the “ndarray”, or N-dimensional array. We can create an array in several ways.

In [2]:
list1 = [1, 2, 3, 4, 5]
arr1 = np.array(list1)
print(arr1)

[1 2 3 4 5]


In [3]:
# Create an array of zeros
zeros_arr = np.zeros(5)
print(zeros_arr)

# Create an array of ones
ones_arr = np.ones(5)
print(ones_arr)

# Create an array of random values between 0 and 1
rand_arr = np.random.rand(5)
print(rand_arr)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.69024058 0.82565173 0.82387809 0.19454457 0.97856382]


## Indexing and Slicing NumPy Arrays
We can access individual elements of a NumPy array using indexing. Indexing in NumPy is zero-based, meaning that the first element has an index of 0, the second element has an index of 1, and so on.

In [4]:
print(arr1[0])
print(arr1[3])

1
4


We can also slice NumPy arrays to select a range of values. Slicing in NumPy is similar to slicing in Python lists.

In [5]:
# Slice elements 1 through 3
print(arr1[1:4])

# Slice elements 0 through 2
print(arr1[:3])

# Slice elements 2 through the end
print(arr1[2:])

[2 3 4]
[1 2 3]
[3 4 5]


## Matrix and vector

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

vector = np.array([1, 2, 3])
print(vector)

# matrix vector multiplication
print(matrix.dot(vector))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[14 32 50]


## Element-wise Operations
NumPy provides a variety of functions for performing element-wise operations on arrays. Element-wise operations allow us to apply an operation to each element in an array individually, rather than to the entire array as a whole.

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add two arrays
print(arr1 + arr2)

# Subtract two arrays
print(arr2 - arr1)

# Multiply two arrays
print(arr1 * arr2)

# Divide two arrays
print(arr2 / arr1)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]


NumPy also allows us to perform element-wise operations on arrays of different shapes and sizes using a technique called broadcasting. Broadcasting allows us to apply an operation to two arrays with different shapes, as long as the shapes can be aligned in a way that makes sense.

In [8]:
arr1 = np.array([1, 2, 3])
scalar = 2

# Add a scalar to an array
print(arr1 + scalar)

# Multiply an array by a scalar
print(arr1 * scalar)

[3 4 5]
[2 4 6]


## Universal Functions
NumPy provides many universal functions that can be used to perform element-wise operations on arrays. These functions are optimized for speed and can be used on arrays of any size.



In [9]:
arr1 = np.array([1, 2, 3])

# Compute the square root of each element in the array
print(np.sqrt(arr1))

# Compute the exponential of each element in the array
print(np.exp(arr1))

# Compute the sine of each element in the array
print(np.sin(arr1))

# Compute the logarithm of each element in the array
print(np.log(arr1))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


## Shape and Reshaping Arrays
In NumPy, we find the shape and reshape an array as follows.

In [10]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# show shape of arr1
print(arr1.shape)

# Reshape the array to a 3x3 matrix
matrix1 = arr1.reshape(3, 3)
print(matrix1.shape)

(9,)
(3, 3)
